# [0]
- name: Include OS-specific variables
  include_vars: Debian.yml

# [1]
- name: Install list of packages
  apt: name={{item}} state=present
  with_items: "{{ packages }}"
  become: yes

- include: common.yml
