# ##
# ansible-playbook playbooks/start_services.yml -i playbooks/hosts --ask-vault-pass --extra-vars "ansible_sudo_pass=YOUR_REMOTE_PASSWD"
# ##

  - name: Start Nagios on Debian Stretch
    hosts: monitors
    connection: local
    gather_facts: False

    tasks:
      # [1]
      - name: Start Apache
        service:
          name: apache2
          state: started
        become: yes

      # [2]
      - name: Start Nagios
        service:
          name: nagios
          state: started
        become: yes
